# Generated by Django 5.1.3 on 2024-11-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(max_length=255)),
                ('complaint_details', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='complaint_images/')),
                ('assigned_team_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('availability_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('SubAdmin', 'Sub Admin'), ('User', 'User'), ('TeamLeader', 'Team Leader'), ('TeamMember', 'Team Member')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfResolution',
            fields=[
                ('proof_id', models.AutoField(primary_key=True, serialize=False)),
                ('proof_image', models.ImageField(upload_to='proof_images/')),
                ('proof_description', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='SubAdministrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('assigned_complaints', models.ManyToManyField(to='civicfixDb.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('complaint_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('proof_id', models.IntegerField()),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.complaint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.team')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('notification_message', models.TextField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.user')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.user'),
        ),
    ]
