# Generated by Django 5.1.3 on 2024-11-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
