# Generated by Django 5.1.3 on 2024-11-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0004_user_alter_complaint_user_alter_feedback_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
