# Generated by Django 5.1.3 on 2024-11-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0005_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
