# Generated by Django 5.1.3 on 2024-11-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0007_user_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
