# Generated by Django 5.1.3 on 2024-11-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
