# Generated by Django 5.1.3 on 2024-11-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0010_rename_user_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(),
        ),
    ]
