# Generated by Django 5.1.3 on 2024-11-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0012_rename_user_complaint_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
