# Generated by Django 5.1.3 on 2024-11-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0013_alter_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_details',
            field=models.CharField(max_length=255),
        ),
    ]
