# Generated by Django 5.1.3 on 2024-11-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0014_complaint_complaint_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_details',
            field=models.TextField(),
        ),
    ]
