# Generated by Django 5.1.3 on 2024-11-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0016_complaint_meter_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='meter_number',
            new_name='ref_number',
        ),
    ]
