# Generated by Django 5.1.3 on 2024-11-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0017_rename_meter_number_complaint_ref_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='image',
            new_name='upload_image',
        ),
    ]
