# Generated by Django 5.1.3 on 2024-11-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0018_rename_image_complaint_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='upload_image',
            new_name='image',
        ),
    ]
