# Generated by Django 5.1.3 on 2024-11-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0019_rename_upload_image_complaint_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='image',
            new_name='upload_image',
        ),
    ]
