# Generated by Django 5.1.3 on 2024-11-30 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0020_rename_image_complaint_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civicfixDb.department'),
        ),
    ]
