# Generated by Django 5.1.3 on 2024-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0021_complaint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact',
            field=models.CharField(max_length=25),
        ),
    ]
