# Generated by Django 5.1.5 on 2025-03-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0023_role_rename_team_id_team_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAdministrator',
        ),
    ]
