# Generated by Django 5.1.5 on 2025-03-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0024_delete_subadministrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='assigned_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civicfixDb.team'),
        ),
    ]
