# Generated by Django 5.1.5 on 2025-03-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0026_remove_customuser_role_teamuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
