# Generated by Django 5.1.5 on 2025-03-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0028_admin_subadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='is_subadmin',
        ),
    ]
