# Generated by Django 5.1.5 on 2025-03-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0029_remove_admin_created_at_remove_admin_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamuser',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
