# Generated by Django 5.1.5 on 2025-03-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0030_remove_teamuser_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_status',
            field=models.CharField(blank=True, choices=[('closed', 'CLOSED'), ('completed', 'COMPLETED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('in_progress', 'IN PROGRESS'), ('resolved', 'RESOLVED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
