# Generated by Django 5.1.5 on 2025-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0031_alter_complaint_resolved_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
