# Generated by Django 5.1.5 on 2025-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0032_alter_complaint_resolved_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofresolution',
            name='proof_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
