# Generated by Django 5.1.5 on 2025-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicfixDb', '0034_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
