export const SNGPL_COMPLAINT_OPTIONS = [
  {
    label: 'Billing Complaint',
    value: '1',
    types: [
      {label: 'Incorrect Meter Reading', value: 'C-INCRCTREAD'},
      {label: 'Interchange Billing', value: 'C-INTRCHNGBIL'},
      {label: 'Minimum Gas Billing', value: 'C-MINGASBIL'},
      {label: 'Wrong Billing', value: 'C-WRNGBILL'},
      {label: 'Adjustment of Tariff (Type/ Period/ Slabs)', value: 'C-TARIFADJ'},
      {label: 'Wrong/Incomplete Name', value: 'C-WRNGNAME'},
      {label: 'Punching Error', value: 'C-PNCHERROR'},
      {label: 'Bill Not Received', value: 'C-BILNOTREC'},
      {label: 'Late Delivery of Bills', value: 'C-LATDELBIL'},
      {label: 'Payment Not Reflected', value: 'C-PAYNTREF'},
      {label: 'Bills withheld by system', value: 'C-BILWITHELD'},
      {label: 'Incorrect Meter Number', value: 'C-WRNGMTRNO'},
      {label: 'Wrong Delivery of Bills', value: 'C-WRNGDELBIL'},
      {label: 'High Gas Billing', value: 'C-HIGASBILL'},
      {label: 'Wrong Adjustment', value: 'C-WRNGADJ'},
      {label: 'Delayed/ Wrong Final Billing', value: 'C-DELFINBILL'},
    ],
  },
  {
    label: 'Sales Complaints',
    value: '2',
    types: [
      {label: 'Incorrect Meter Reading', value: 'C-INCRCTREAD'},
      {label: 'Interchange Billing', value: 'C-INTRCHNGBIL'},
      {label: 'Minimum Gas Billing', value: 'C-MINGASBIL'},
      {label: 'Wrong Billing', value: 'C-WRNGBILL'},
      {label: 'Adjustment of Tariff (Type/ Period/ Slabs)', value: 'C-TARIFADJ'},
      {label: 'Wrong/Incomplete Name', value: 'C-WRNGNAME'},
      {label: 'Punching Error', value: 'C-PNCHERROR'},
      {label: 'Bill Not Received', value: 'C-BILNOTREC'},
      {label: 'Late Delivery of Bills', value: 'C-LATDELBIL'},
      {label: 'Payment Not Reflected', value: 'C-PAYNTREF'},
      {label: 'Bills withheld by system', value: 'C-BILWITHELD'},
      {label: 'Incorrect Meter Number', value: 'C-WRNGMTRNO'},
      {label: 'Wrong Delivery of Bills', value: 'C-WRNGDELBIL'},
      {label: 'High Gas Billing', value: 'C-HIGASBILL'},
      {label: 'Wrong Adjustment', value: 'C-WRNGADJ'},
      {label: 'Delayed/ Wrong Final Billing', value: 'C-DELFINBILL'},
    ],
  },
  {
    label: 'Gas Distribution Issues Ind/Com',
    value: '3',
    types: [
      {label: 'Service Valve Damage', value: 'DIS-SRVL-DAM-I'},
      {label: 'Leakage at Meter', value: 'DIS-LK-MTR-I'},
      {label: 'Service Valve Buried', value: 'DIS-SRVL-BUR-I'},
      {label: 'Line Rupture', value: 'DIS-LIN-RUP-I'},
      {label: 'Fire Case', value: 'DIS-FIRECASE-I'},
      {label: 'High Pressure Area', value: 'DIS-HIPRESAREA-I'},
      {label: 'High Pressure', value: 'DIS-HIPRES-I'},
      {label: 'Meter Stop', value: 'DIS-MTR-STP-I'},
      {label: 'Main Line Leak', value: 'DIS-MAIN-LK-I'},
      {label: 'Regulator Damage', value: 'DIS-REG-DAM-I'},
      {label: 'Clamped', value: 'DIS-CLAMPD-I'},
      {label: 'Meter Block', value: 'DIS-MTR-BLK-I'},
      {label: 'Riser Bend', value: 'DIS-RISR BND-I'},
      {label: 'Leakage at Regulator', value: 'DIS-LK-REG-I'},
      {label: 'Under Ground Leakage', value: 'DIS-UG-LK-I'},
      {label: 'Gas Stop', value: 'DIS-GAS-STOP-I'},
      {label: 'Meter Damage', value: 'DIS-MTR-DAM-I'},
      {label: 'Leakage at TBS / DRS', value: 'DIS-LKTBS-I'},
      {label: 'Uplifting', value: 'DIS-UPLIFT-I'},
      {label: 'Low Pressure Area', value: 'DIS-LOPRESAREA-I'},
      {label: 'Meter Replace for Flow Proving', value: 'DIS-MTR-REP-I'},
      {label: 'Regulator Overflow', value: 'DIS-REGOVRFLW-I'},
      {label: 'Leakage at Service Valve', value: 'DIS-LK-SVL-I'},
      {label: 'Low Pressure', value: 'DIS-LOWPRES-I'},
      {label: 'Riser Leak', value: 'DIS-RISR LK-I'},
      {label: 'Valve Pit Cover Missing', value: 'DIS-VALPITCVR-I'},
      {label: 'Gas Leakage', value: 'DIS-LK-GAS-I'},
    ],
  },
  {
    label: 'Customer Services',
    value: '4',
    types: [
      {label: 'Main Line Leak', value: 'C-MAINLK'},
      {label: 'Riser Leak', value: 'C-RISLK'},
      {label: 'Uplifting of CMS / Service Valve', value: 'R-CMSUPLFT'},
      {label: 'High Pressure', value: 'C-HIPRS'},
      {label: 'Regulator Damage', value: 'C-REGDAM'},
      {label: 'Condensate / Oil from service line', value: 'C-OILSL'},
      {label: 'Leakage at Regulator', value: 'C-REGLK'},
      {label: 'TBS/DRS Low Pressure', value: 'C-TBSLOPRS'},
      {label: 'HGBC - High Gas Billing Case', value: 'C-HIGHBILL'},
      {label: 'TBS/DRS Fire Case', value: 'C-TBSFIRE'},
      {label: 'Low Pressure Area', value: 'C-LOPRSA'},
      {label: 'Service Tee Choke', value: 'C-SRTEEC'},
      {label: 'TBS/DRS High Pressure', value: 'C-TBSHIPRS'},
      {label: 'CMS Shifting/Modification', value: 'R-CMSSHFT'},
      {label: 'Leakage at TBS / DRS', value: 'C-TBSLK'},
      {label: 'Under Ground Leakage', value: 'C-UGNDLK'},
      {label: 'Regulator Overflow', value: 'C-REGOVF'},
      {label: 'Service Valve Buried', value: 'C-SVBUR'},
      {label: 'Leakage at Service Valve', value: 'C-SVLK'},
      {label: 'Meter Damage', value: 'C-MTRDAM'},
      {label: 'Blast', value: 'C-BLAST'},
      {label: 'Emergency - (Non Consumer)', value: 'EMR-NONCONSM'},
      {label: 'Gas Stop', value: 'C-GSTOP'},
      {label: 'Building Collapse', value: 'C-BLDCOL'},
      {label: 'Line Rupture', value: 'C-LINRUP'},
      {label: 'Service Valve Damage', value: 'C-SVDAM'},
      {label: 'Fire Case', value: 'C-FIRE'},
      {label: 'Leakage at Meter', value: 'C-MTRLK'},
      {label: 'Meter Block', value: 'C-MTRBLK'},
      {label: 'High Pressure Area', value: 'C-HIPRSA'},
      {label: 'TBS/DRS Rupture', value: 'C-TBSRUP'},
      {label: 'Riser Bend', value: 'C-RISBND'},
      {label: 'Gas Theft / Violation Of Contract', value: 'C-SLTHFT'},
      {label: 'Valve Pit Cover Missing', value: 'C-VLCVMIS'},
      {label: 'Low Pressure', value: 'C-LOPRS'},
      {label: 'Clamped', value: 'R-CLAMP'},
      {label: 'Gas Leakage', value: 'C-GASLK'},
      {label: 'Meter Stop', value: 'C-MTRSTOP'},
    ],
  },
];

export const LESCO_COMPLAINT_OPTIONS = [
  {
    label: 'Line Complaints',
    value: '1',
    types: [
      {label: 'Power Outage', value: '1'},
      {label: 'Damaged Meter', value: '2'},
      {label: 'Electric Fire', value: '3'},
      {label: 'Fluctuation', value: '4'},
      {label: 'Line Fault', value: '5'},
      {label: 'Low/ High Voltage - Short Term', value: '6'},
      {label: 'Low/ High Voltage - Long Term', value: '7'},
      {label: 'Phase Issue', value: '8'},
      {label: 'Additional Feeder', value: '9'},
      {label: 'Damaged Transformer - Rural', value: '10'},
      {label: 'Damaged Transformer - Urban', value: '11'},
      {label: 'Transformer Relocation/Augmentation', value: '12'},
      {label: 'Additional Transformer', value: '13'},
      {label: 'Live Fallen Wire', value: '14'},
      {label: 'Service Line Reloc/Improve - Short Term', value: '15'},
      {label: 'LT/HT Line Relocation/Improvement- Long Term', value: '16'},
      {label: 'Meter Sparking/Wire Loose', value: '17'},
      {label: 'Permanent Rectification of Temporary Fix', value: '18'},
      {label: 'Tripping (Due to Transformer)', value: '19'},
      {label: 'Transformer Oil Leakage', value: '84'},
      {label: 'Leakage of current', value: '86'},
    ],
  },
  {
    label: 'Non-Line Complaints',
    value: '2',
    types: [
      {label: 'Meter Position', value: '20'},
      {label: 'Detection Bill', value: '21'},
      {label: 'Delayed Billing (New Connection)', value: '22'},
      {label: 'Late/Non-Delivery of Bill', value: '23'},
      {label: 'Electricity Theft', value: '24'},
      {label: 'Installed Transformer/Meter/Wire Theft', value: '25'},
      {label: 'Bulk Distribution Theft', value: '26'},
      {label: 'Vehicle Theft', value: '27'},
      {label: 'Violation of Energy Conservation Measures', value: '28'},
      {label: 'Electrical Safety', value: '29'},
      {label: 'Defective Meter (1-phase)', value: '30'},
      {label: 'Defective Meter (3-phase)', value: '31'},
      {label: 'Wrong Meter Reading', value: '32'},
      {label: 'No Meter Reading Taken', value: '33'},
      {label: 'Excess Billing', value: '34'},
      {label: 'Under Billing', value: '35'},
      {label: 'Account Information', value: '36'},
      {label: 'Bribery/Corruption', value: '37'},
      {label: 'Delayed Meter Reading', value: '38'},
      {label: 'Change of Name', value: '82'},
    ],
  },
  {
    label: 'Leads / Requests',
    value: '3',
    types: [
      {label: 'Additional Transformer', value: '39'},
      {label: 'Temporary Connection', value: '40'},
      {label: 'Relocation of Meter', value: '41'},
      {label: 'New Connection', value: '42'},
      {label: 'Reconnection', value: '43'},
      {label: 'Change of Sanctioned Load', value: '44'},
      {label: 'Electrification', value: '45'},
      {label: 'Loadshedding Schedule', value: '46'},
      {label: 'Change of Tariff', value: '47'},
      {label: 'Replacement Distribution Box', value: '48'},
      {label: 'Other', value: '79'},
      {label: 'Net Metering', value: '87'},
    ],
  },
];
